apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx-ingress"
  namespace: "2048-game"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: cs-1.preprod,cs-2.preprod,cs-3.preprod
    alb.ingress.kubernetes.io/security-groups: preprod.onprem,preprod.cs,preprod.web
  labels:
    app: 2048-nginx-ingress
spec:
  rules:
  - host: 2048.tmaws.io
    http:
      paths:
      - path: /
        backend:
          serviceName: "service-2048"
          servicePort: 80
