site_name: AWS Load Balancer Controller
repo_name: kubernetes-sigs/aws-load-balancer-controller
repo_url: https://github.com/kubernetes-sigs/aws-load-balancer-controller
edit_uri: edit/main/docs/
strict: true

nav:
  - Home:
    - Welcome: index.md
    - How it works: how-it-works.md
  - Documentation:
    - Deployment:
      - Installation Guide: deploy/installation.md
      - Configurations: deploy/configurations.md
      - Subnet Discovery: deploy/subnet_discovery.md
      - Pod Readiness Gate: deploy/pod_readiness_gate.md
      - Migrate v1 to v2: deploy/upgrade/migrate_v1_v2.md
    - Reference:
        - Ingress:
            - Annotations: reference/ingress/annotations.md
            - Specification: reference/ingress/spec.md
            - IngressClass: reference/ingress/ingress_class.md
            - Certificate Discovery: reference/ingress/cert_discovery.md
        - Service:
            - Network Load Balancer: reference/service/nlb.md
            - Annotations: reference/service/annotations.md
        - TargetGroupBinding:
            - TargetGroupBinding: reference/targetgroupbinding/targetgroupbinding.md
            - Specification: reference/targetgroupbinding/spec.md
    - Tasks:
      - Example EchoServer: tasks/echo_server.md
      - Example gRPCServer: tasks/grpc_server.md
      - RBAC to access OIDC Secret: tasks/secrets_access.md
      - Cognito Authentication: tasks/cognito_authentication.md
      - SSL Redirect: tasks/ssl_redirect.md
      - NLB TLS Termiation: tasks/nlb_tls_termination/index.md
      - Externally Managed Load Balancer: tasks/self_managed_lb/index.md



plugins:
  - search
theme:
  name: material
  language: en
  favicon: assets/images/aws_load_balancer_icon.svg
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  custom_dir: docs/theme_overrides
# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
extra_javascript:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js
