apiVersion: v1
name: aws-alb-ingress-controller
description: A Helm chart for AWS ALB Ingress Controller
version: 0.1.4
appVersion: "v1.0.1"
engine: gotpl
home: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
sources:
  - https://github.com/kubernetes-sigs/aws-alb-ingress-controller
keywords:
  - aws
  - ingress
maintainers:
  - name: Kraig Amador
    email: kraig.amador@ticketmaster.com
  - name: Andrew Tandoc
    email: tandoca@amazon.com
  - name: Yang Yang
    email: yyyng@amazon.com