name: Unit Test
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
 
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        sudo snap install yq
        make test
        
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./cover.out # optional

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: make quick-ci
        run: |
          make quick-ci

  deprecated-apigroups:
    name: Detect deprecated apiGroups
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          version=$(curl -sL https://api.github.com/repos/FairwindsOps/pluto/releases/latest | jq -r ".tag_name")
          number=${version:1}
          wget https://github.com/FairwindsOps/pluto/releases/download/${version}/pluto_${number}_linux_amd64.tar.gz
          sudo tar -C /usr/local -xzf pluto_${number}_linux_amd64.tar.gz
      - run: |
          rm -rf docs/install
          rm -rf config/samples
          /usr/local/pluto detect-files -d .